import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const neueRegrade = localFont({
  src: [
    {
      path: "./fonts/Neue Regrade Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Neue Regrade Regular Italic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/Neue Regrade Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Neue Regrade Semibold.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-neue-regrade",
  fallback: ["Arial", "Helvetica", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Cocao Mobile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${neueRegrade.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
